app:
  user:
    name_max_length: 50
    email_max_length: 255
    password_min_length: 6
    size_gravatar: 50
    page: 10
  session:
    one: 1
  micropost:
    content_max: 140
    size_gravatar: 50
    fivemegabyte: 5
size_gravatar: 70
config:
  development:
    port: "587"
    host: "localhost:3000"
views:
  micropost:
    accept: "image/jpeg, image/gif, image/png"
