app:
  user:
    name_max_length: 50
    email_max_length: 255
    password_min_length: 6
    size_gravatar: 50
    page: 10
  session:
    one: 1
config:
  development:
    port: "587"
    host: "localhost:3000"

